/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

#define MAX 4000000

int main(){
    unsigned long a = 1;
    unsigned long b = 2;
    unsigned long fib = 0;
    // sum initialized because the first 3 values (1, 1, 2) are fixed
    unsigned long sum = 2;
    unsigned char i = 4;

    while(a+b < MAX){
        fib = a + b;
        a = b;
        b = fib;
        // if result is even
        if(fib%2 == 0){
            sum += fib;
        }
        printf("%d: value:%lu / sum:%lu\n",i, fib, sum);
        i++;
    }
    printf("\nRESULT: %lu\n", sum); 
    return 0;
}
